# Generated by Django 5.1.15 on 2026-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='letterhead',
            field=models.ImageField(blank=True, help_text='Image du papier à en-tête pour les rapports PDF', null=True, upload_to='letterheads/', verbose_name='papier à en-tête'),
        ),
    ]
