# Generated by Django 6.0.2 on 2026-03-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dernière IP de connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ua',
            field=models.TextField(blank=True, verbose_name='dernier agent utilisateur'),
        ),
    ]
