# Generated by Django 5.1.15 on 2026-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_ticket_attachment_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='note interne'),
        ),
    ]
