# Generated by Django 5.1.15 on 2026-02-14 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0007_property_budget_total_property_charges_mensuelles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFLOW', 'Entrée (Revenu)'), ('OUTFLOW', 'Sortie (Dépense)')], default='INFLOW', max_length=10, verbose_name='type de mouvement')),
                ('category', models.CharField(choices=[('RENT', 'Loyer perçu'), ('COMMISSION', 'Commission MaDis'), ('MAINTENANCE', 'Maintenance / Réparation'), ('TAX', 'Taxe / Impôt'), ('INSURANCE', 'Assurance'), ('PROMOTION_SALE', 'Vente (Promotion)'), ('OTHER', 'Autre')], default='RENT', max_length=20, verbose_name='catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant (€)')),
                ('date', models.DateField(verbose_name='date de transaction')),
                ('description', models.TextField(blank=True, verbose_name='description / notes')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='finance/invoices/%Y/%m/', verbose_name='pièce jointe / facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='properties.property', verbose_name='bien immobilier')),
            ],
            options={
                'verbose_name': 'Transaction Financière',
                'verbose_name_plural': 'Transactions Financières',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
