# Generated by Django 5.1.15 on 2026-02-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois concerné'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='period_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='année concernée'),
        ),
    ]
