# Generated by Django 5.1.15 on 2026-02-14 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialtransaction_period_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='finance.financialtransaction', verbose_name='transaction parente'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.CharField(choices=[('RENT', 'Loyer perçu'), ('COMMISSION', 'Commission MaDis'), ('MAINTENANCE', 'Maintenance / Réparation'), ('CHARGES', 'Charges mensuelles'), ('TAX', 'Taxe / Impôt'), ('INSURANCE', 'Assurance'), ('PROMOTION_SALE', 'Vente (Promotion)'), ('OTHER', 'Autre')], default='RENT', max_length=20, verbose_name='catégorie'),
        ),
    ]
