# Generated by Django 5.1.15 on 2026-02-15 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialtransaction_parent_transaction_and_more'),
        ('properties', '0011_property_devise_origine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.CharField(choices=[('RENT', 'Loyer perçu'), ('COMMISSION', 'Commission MaDis'), ('MAINTENANCE', 'Maintenance / Réparation'), ('CHARGES', 'Charges mensuelles'), ('TAX', 'Taxe / Impôt'), ('INSURANCE', 'Assurance'), ('PROMOTION_SALE', 'Vente (Promotion)'), ('CASH_CALL', 'Appel de fonds (Encaissement)'), ('SETTLEMENT', 'Reversement (Décaissement)'), ('OTHER', 'Autre')], default='RENT', max_length=20, verbose_name='catégorie'),
        ),
        migrations.CreateModel(
            name='CashCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant demandé (€)')),
                ('reason', models.CharField(max_length=255, verbose_name='motif')),
                ('description', models.TextField(blank=True, verbose_name='description / détails')),
                ('due_date', models.DateField(verbose_name='date limite')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('PAID', 'Payé / Reçu'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_calls', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_calls', to='properties.property', verbose_name='bien immobilier')),
            ],
            options={
                'verbose_name': 'Appel de Fonds',
                'verbose_name_plural': 'Appels de Fonds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='cash_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashcall', verbose_name='appel de fonds lié'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant versé (€)')),
                ('period_start', models.DateField(verbose_name='début période')),
                ('period_end', models.DateField(verbose_name='fin période')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROCESSING', 'En cours'), ('PAID', 'Versé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence virement')),
                ('note', models.TextField(blank=True, verbose_name='note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='properties.property', verbose_name='bien immobilier')),
            ],
            options={
                'verbose_name': 'Reversement',
                'verbose_name_plural': 'Reversements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.settlement', verbose_name='reversement lié'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='solde actuel (€)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='properties.property', verbose_name='bien immobilier')),
            ],
        ),
    ]
