# Generated by Django 5.1.15 on 2026-02-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_alter_constructionsite_status'),
        ('finance', '0005_financialtransaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='construction.constructionsite', verbose_name='chantier concerné'),
        ),
    ]
