# Generated by Django 5.1.15 on 2026-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financialtransaction_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.CharField(choices=[('RENT', 'Loyer perçu'), ('COMMISSION', 'Commission MaDis'), ('MAINTENANCE', 'Maintenance / Réparation'), ('CHARGES', 'Charges mensuelles'), ('TAX', 'Taxe / Impôt'), ('INSURANCE', 'Assurance'), ('PROMOTION_SALE', 'Vente (Promotion)'), ('CASH_CALL', 'Appel de fonds (Encaissement)'), ('SETTLEMENT', 'Reversement (Décaissement)'), ('MATERIAUX', 'Chantier: Matériaux'), ('MAIN_D_OEUVRE', "Chantier: Main d'œuvre"), ('SERVICES', 'Chantier: Services/Extérieur'), ('OTHER', 'Autre')], default='RENT', max_length=20, verbose_name='catégorie'),
        ),
    ]
