# Generated by Django 5.1.15 on 2026-02-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_financialtransaction_category'),
        ('properties', '0014_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='properties.project', verbose_name='projet concerné'),
        ),
    ]
