# Generated by Django 5.1.15 on 2026-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financialtransaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcall',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='finance/cash_calls/proofs/', verbose_name='justificatif de paiement'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='finance/settlements/proofs/', verbose_name='justificatif de virement'),
        ),
        migrations.AlterField(
            model_name='cashcall',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('PENDING', 'En attente de confirmation'), ('PAID', 'Payé / Reçu'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='statut'),
        ),
    ]
