# Generated by Django 5.1.15 on 2026-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_cashcall_proof_settlement_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcall',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('PENDING', 'En attente de confirmation'), ('PAID', 'Payé / Reçu'), ('REJECTED', 'Justificatif Refusé'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='statut'),
        ),
    ]
