# Generated by Django 5.1.15 on 2026-02-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('address', models.TextField(verbose_name='adresse')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='pays')),
                ('property_type', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('TERRAIN', 'Terrain'), ('IMMEUBLE', 'Immeuble'), ('LOCAL_COMMERCIAL', 'Local commercial'), ('AUTRE', 'Autre')], default='APPARTEMENT', max_length=20, verbose_name='type de bien')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='surface (m²)')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('EN_PROJET', 'En projet')], default='EN_PROJET', max_length=20, verbose_name='statut')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='date de fin estimée')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='budget (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='properties.property', verbose_name='bien')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
