# Generated by Django 5.1.15 on 2026-02-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de chambres'),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
        migrations.AddField(
            model_name='property',
            name='room_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de pièces'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='image')),
                ('is_main', models.BooleanField(default=False, verbose_name='image principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='bien')),
            ],
            options={
                'verbose_name': 'Image du bien',
                'verbose_name_plural': 'Images des biens',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
