# Generated by Django 5.1.15 on 2026-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_country_property_bedroom_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('PROFESSIONNEL', 'Professionnel')], default='RESIDENTIEL', max_length=20, verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_nature',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], default='VENTE', max_length=20, verbose_name='nature de transaction'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('VILLA', 'Villa'), ('BOUTIQUE', 'Boutique / Commerce'), ('BUREAU', 'Bureau'), ('ENTREPOT', 'Entrepôt'), ('LOCAL_ACTIVITE', "Local d'activité"), ('TERRAIN', 'Terrain'), ('IMMEUBLE', 'Immeuble'), ('AUTRE', 'Autre')], default='APPARTEMENT', max_length=20, verbose_name='type de bien'),
        ),
    ]
