# Generated by Django 5.1.15 on 2026-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_owner_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='loyer_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='loyer mensuel (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='prix_nuitee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix par nuit (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix de vente (€)'),
        ),
    ]
