# Generated by Django 5.1.15 on 2026-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_loyer_mensuel_property_prix_nuitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe prélevé par MaDis', max_digits=10, null=True, verbose_name='commission fixe (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage prélevé par MaDis (ex: 10.00)', max_digits=5, null=True, verbose_name='taux de commission (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='commission_type',
            field=models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('FIXE', 'Montant fixe')], default='POURCENTAGE', max_length=15, verbose_name='type de commission'),
        ),
        migrations.AddField(
            model_name='property',
            name='management_type',
            field=models.CharField(choices=[('MANDAT', 'Mandat MaDis'), ('GESTION', 'Gestion locative'), ('CONSTRUCTION', 'Suivi de chantier')], default='MANDAT', max_length=20, verbose_name='type de gestion'),
        ),
    ]
