# Generated by Django 5.1.15 on 2026-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_commission_fixe_property_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='budget total du projet (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='charges_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='charges mensuelles (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='date_debut_travaux',
            field=models.DateField(blank=True, null=True, verbose_name='date de début des travaux'),
        ),
        migrations.AddField(
            model_name='property',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin prévue'),
        ),
        migrations.AddField(
            model_name='property',
            name='depot_garantie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dépôt de garantie (€)'),
        ),
        migrations.AddField(
            model_name='property',
            name='frais_notaire_inclus',
            field=models.BooleanField(default=False, verbose_name='frais de notaire inclus'),
        ),
        migrations.AddField(
            model_name='property',
            name='meuble',
            field=models.BooleanField(default=False, verbose_name='meublé'),
        ),
        migrations.AddField(
            model_name='property',
            name='negociable',
            field=models.BooleanField(default=False, verbose_name='prix négociable'),
        ),
        migrations.AddField(
            model_name='property',
            name='nom_entrepreneur',
            field=models.CharField(blank=True, max_length=255, verbose_name="nom de l'entrepreneur"),
        ),
    ]
