# Generated by Django 5.1.15 on 2026-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_budget_total_property_charges_mensuelles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True, verbose_name="date d'acquisition"),
        ),
    ]
