# Generated by Django 5.1.15 on 2026-02-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_date_acquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prix_acquisition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de base pour le calcul du rendement', max_digits=12, null=True, verbose_name="prix d'acquisition (€)"),
        ),
    ]
