# Generated by Django 5.1.15 on 2026-02-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_prix_acquisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='frais_notaire_inclus',
        ),
        migrations.AddField(
            model_name='property',
            name='frais_acquisition_annexes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frais de notaire, taxes, commissions locales, etc.', max_digits=12, null=True, verbose_name="frais d'acquisition annexes (€)"),
        ),
        migrations.AlterField(
            model_name='property',
            name='prix_acquisition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat hors frais", max_digits=12, null=True, verbose_name="prix d'achat (net vendeur) (€)"),
        ),
    ]
