# Generated by Django 5.1.15 on 2026-02-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_property_frais_notaire_inclus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='devise_origine',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('AED', 'Dirham (AED)'), ('XOF', 'Franc CFA (XOF)'), ('CHF', 'Franc Suisse (CHF)'), ('GBP', 'Livre Sterling (£)')], default='EUR', help_text="Devise de l'investisseur pour conversion temps réel", max_length=5, verbose_name="devise d'origine"),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified_fonciere',
            field=models.BooleanField(default=False, help_text='Certifie que MaDis a validé les titres de propriété', verbose_name='vérifié foncièrement'),
        ),
    ]
