# Generated by Django 5.1.15 on 2026-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_devise_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('VENDU', 'Vendu')], default='PLANIFIE', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('EN_PROJET', 'En projet'), ('VENDU', 'Vendu')], default='EN_PROJET', max_length=20, verbose_name='statut'),
        ),
    ]
