# Generated by Django 5.1.15 on 2026-02-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_project_status_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pending_decision',
            field=models.BooleanField(default=False, help_text='Indique si le nouveau propriétaire doit décider du futur du bien (revente/location)', verbose_name='décision en attente'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('EN_PROJET', 'En projet'), ('VENDU', 'Vendu'), ('LOUE', 'Loué')], default='EN_PROJET', max_length=20, verbose_name='statut'),
        ),
    ]
