# Generated by Django 5.1.15 on 2026-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_pending_decision_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('CONSTRUCTION', 'Construction / Développement'), ('MAINTENANCE', 'Entretien / Rénovation')], default='CONSTRUCTION', max_length=20, verbose_name='catégorie'),
        ),
    ]
