# Generated by Django 5.1.15 on 2026-02-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='devise_origine',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('GNF', 'Franc Guinéen (GNF)'), ('AED', 'Dirham (AED)'), ('XOF', 'Franc CFA (XOF)'), ('XAF', 'Franc CFA (BEAC)'), ('CNY', 'Yuan Chinois (¥)'), ('CHF', 'Franc Suisse (CHF)'), ('GBP', 'Livre Sterling (£)')], default='EUR', help_text="Devise de l'investisseur pour conversion temps réel", max_length=5, verbose_name="devise d'origine"),
        ),
    ]
