# Generated by Django 5.1.15 on 2026-02-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_property_devise_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('Guinée', 'Guinée'), ('France', 'France'), ('Chine', 'Chine'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Royaume-Uni', 'Royaume-Uni'), ('États-Unis', 'États-Unis'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Sénégal', 'Sénégal'), ('Cameroun', 'Cameroun')], default='Guinée', max_length=50, verbose_name='pays'),
        ),
    ]
