# Generated by Django 5.1.15 on 2026-02-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
    ]
