# Generated by Django 5.1.15 on 2026-02-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom du chantier')),
                ('address', models.TextField(blank=True, verbose_name='adresse du chantier')),
                ('status', models.CharField(choices=[('PREPARATION', 'En préparation'), ('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé')], default='PREPARATION', max_length=20, verbose_name='statut')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='progression (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_sites', to='properties.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('content', models.TextField(verbose_name='contenu')),
                ('weather', models.CharField(blank=True, choices=[('ENSOLEILLE', 'Ensoleillé'), ('NUAGEUX', 'Nuageux'), ('PLUIE', 'Pluie'), ('VENT', 'Vent'), ('NEIGE', 'Neige'), ('ORAGE', 'Orage')], max_length=20, verbose_name='météo')),
                ('workers_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'ouvriers")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='construction.constructionsite', verbose_name='chantier')),
            ],
            options={
                'verbose_name': 'Entrée de journal',
                'verbose_name_plural': 'Entrées de journal',
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100, verbose_name='phase')),
                ('percentage', models.PositiveIntegerField(verbose_name='progression (%)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='date de mise à jour')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='construction.constructionsite', verbose_name='chantier')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'Mise à jour de progression',
                'verbose_name_plural': 'Mises à jour de progression',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction/photos/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='date de prise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='construction.journalentry', verbose_name='entrée de journal')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='construction.constructionsite', verbose_name='chantier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_photos', to=settings.AUTH_USER_MODEL, verbose_name='uploadé par')),
            ],
            options={
                'verbose_name': 'Photo de chantier',
                'verbose_name_plural': 'Photos de chantier',
                'ordering': ['-created_at'],
            },
        ),
    ]
