# Generated by Django 5.1.15 on 2026-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
    ]
