# Generated by Django 5.1.15 on 2026-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_constructionsite_city_constructionsite_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='budget estimé (€)'),
        ),
    ]
