# Generated by Django 5.1.15 on 2026-02-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_constructionsite_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description du jalon')),
                ('completed', models.BooleanField(default=False, verbose_name='terminé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='construction.constructionsite', verbose_name='chantier')),
            ],
            options={
                'verbose_name': 'Jalon',
                'verbose_name_plural': 'Jalons',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
