# Generated by Django 5.1.15 on 2026-02-14 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='chef_de_chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_sites', to=settings.AUTH_USER_MODEL, verbose_name='chef de chantier'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_milestones', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
    ]
