# Generated by Django 5.1.15 on 2026-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_constructionsite_chef_de_chantier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='milestone',
            name='responsible',
            field=models.CharField(blank=True, help_text='Nom de la personne responsable de ce jalon', max_length=100, verbose_name='responsable'),
        ),
    ]
