# Generated by Django 5.1.15 on 2026-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_remove_milestone_assigned_to_milestone_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsite',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'En préparation'), ('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PREPARATION', max_length=20, verbose_name='statut'),
        ),
    ]
