# Generated by Django 5.1.15 on 2026-02-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_alter_constructionsite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='motif de suspension'),
        ),
    ]
