# Generated by Django 5.1.15 on 2026-02-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='fichier')),
                ('category', models.CharField(choices=[('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('PLAN', 'Plan'), ('PHOTO', 'Photo'), ('ADMINISTRATIF', 'Administratif'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.project', verbose_name='projet')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='bien')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
