# Generated by Django 5.1.15 on 2026-02-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_alter_constructionsite_status'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='construction.constructionsite', verbose_name='chantier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('PLAN', 'Plan'), ('PHOTO', 'Photo'), ('ADMINISTRATIF', 'Administratif'), ('VERIF_FONCIERE', 'Vérification Foncière / Titres'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='catégorie'),
        ),
    ]
