# Generated by Django 6.0.2 on 2026-03-01 21:44

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_site_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[documents.models.validate_file_type], verbose_name='fichier'),
        ),
    ]
